# MIT License
#
# Copyright (c) 2025 Cronomantic
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
"""Writer for the ReGAC source format: database dictionary -> source text."""

from .conds import render_block

NOWHERE = 0
CARRIED = 255


ESCAPES = {
    chr(0): chr(92) + "0",
    chr(34): chr(92) + chr(34),
    chr(92): chr(92) + chr(92),
}


def quote_char(c):
    """Quote a single character for the /CTL punctuation list."""
    return chr(34) + ESCAPES.get(c, c) + chr(34)


def _ids(d):
    """Sort a dictionary keyed by stringified integers by numeric value."""
    return sorted(d.items(), key=lambda kv: int(kv[0]))


class SourceWriter:
    def __init__(self, ddb, name="adventure"):
        self.ddb = ddb
        self.name = name
        self.out = []
        # id -> preferred word, for rendering connections readably.
        self.verb_word = {}
        for word, vid in ddb.get("verbs", {}).items():
            prev = self.verb_word.get(vid)
            if prev is None or len(word) > len(prev):
                self.verb_word[vid] = word

    def w(self, line=""):
        self.out.append(line)

    def wtext(self, line):
        """Write a line of adventure text, escaping it if it would otherwise
        be read back as a marker."""
        self.out.append("|" + line if line[:1] in ("#", "/", ";", "|") else line)

    def text(self):
        return "\n".join(self.out) + "\n"

    def generate(self):
        self.header()
        self.ctl()
        self.voc()
        self.msg()
        self.obj()
        self.loc()
        self.conds("HIGH", self.ddb.get("hpcs", []))
        self.conds("LOW", self.ddb.get("lpcs", []))
        self.gfx()
        self.font()
        return self.text()

    def header(self):
        self.w(f"; ReGAC source -- {self.name}")
        self.w("; Generated by regac. Edit freely; the compiler reads this back.")
        self.w()

    def ctl(self):
        d = self.ddb
        self.w("/CTL")
        self.w(f"model    {d.get('model', 'SPECTRUM')}")
        self.w(f"charset  {d.get('charset', 'ascii')}")
        self.w(f"start    {d.get('init_loc', 1)}")
        self.w(f"width    {d.get('width', 32)}")
        punct = " ".join(quote_char(c) for c in d.get("punctuation", []))
        self.w(f"punct    {punct}")
        sep = " ".join(f'"{s}"' for s in d.get("separators", []))
        self.w(f"sep      {sep}")
        self.w(f'nothing  "{d.get("no_objs_msg", "Nothing")}"')
        self.w()

    def voc(self):
        self.w("/VOC")
        self.w("; word                    id  type")
        groups = [
            ("verb", self.ddb.get("verbs", {})),
            ("noun", self.ddb.get("nouns", {})),
            ("adverb", self.ddb.get("adverbs", {})),
        ]
        for kind, words in groups:
            if not words:
                continue
            for word, wid in sorted(words.items(), key=lambda kv: (kv[1], kv[0])):
                self.w(f"{word:<24} {wid:>3}  {kind}")
            self.w()
        for word in self.ddb.get("pronouns", []):
            self.w(f"{word:<24} 255  noun")

    def msg(self):
        self.w("/MSG")
        for mid, text in _ids(self.ddb.get("messages", {})):
            self.w(f"#{mid}")
            self.wtext(text)
        self.w()

    def obj(self):
        self.w("/OBJ")
        for oid, o in _ids(self.ddb.get("objects", {})):
            start = o.get("initial_loc", 0)
            where = {NOWHERE: "nowhere", CARRIED: "carried"}.get(start, str(start))
            self.w(f"#{oid}  weight={o.get('weight', 0)}  start={where}")
            self.wtext(o.get("name", ""))
        self.w()

    def loc(self):
        lcs = self.ddb.get("lcs", {})
        for lid, l in _ids(self.ddb.get("locations", {})):
            self.w(f"/LOC #{lid}  gfx={l.get('graphic_id', 0)}")
            self.wtext(l.get("desc", ""))
            exits = l.get("exits", [])
            if exits:
                self.w("  /CONN")
                for e in exits:
                    word = self.verb_word.get(e["dir"], str(e["dir"]))
                    self.w(f"    {word:<12} {e['dest']}")
            local = lcs.get(str(lid)) or lcs.get(lid)
            if local:
                self.w("  /LOCAL")
                for line in render_block(local):
                    self.w(f"    {line}")
            self.w()

    def conds(self, section, block):
        self.w(f"/{section}")
        for line in render_block(block):
            self.w(line)
        self.w()

    def gfx(self):
        gfx = self.ddb.get("gfx", {})
        if not gfx:
            return
        self.w("/GFX")
        for gid, insts in _ids(gfx):
            self.w(f"#{gid}")
            for inst in insts:
                args = " ".join(str(a) for a in inst[1:])
                self.w(f"  {inst[0]}{' ' + args if args else ''}")
            self.w()

    def font(self):
        font = self.ddb.get("font", [])
        if not font or not any(font):
            return
        self.w(f"/FONT chars={len(font) // 8}")
        for code in range(len(font) // 8):
            row = font[code * 8 : code * 8 + 8]
            if not any(row):
                continue
            glyph = chr(code) if 32 <= code < 127 else "?"
            hexes = " ".join(f"{b:02X}" for b in row)
            self.w(f"#{code:<4} {hexes}   ; {glyph}")
        self.w()


def generate(ddb, name="adventure"):
    return SourceWriter(ddb, name).generate()
